In [1]:
#PHYS 213
#Assignment 7
#Anne Xie
#Student Number: 20125978

In [1]:
#Question 1

#import libraries
import numpy as np

#Make first matrix
v1 = np.array([[3,2,-1]])
v2 = np.array ([[4,0,-3]])
v3 = np.array([[7,3,1]])
v4 = np.array([[-2,-5,3]])
m1 = np.vstack([v1,v2,v3,v4])

#Make second matrix
v5 = np.array([[6,7]])
v6 = np.array([[3,4]])
v7 = np.array([[2,3]])
m2 = np.vstack([v5,v6,v7])


def matrix(m,n): #define function to do matrix multiplication
    u = np.zeros((len(m),len(n[1])))
                 
    for k in range(len(n[1])): #loop over each column of the second matrix
        for i in range(len(m)): #loop over each row of the first matrix
            for j in range(len(n)): #loop over each element in each row of the first matrix
                u[i][k] += m[i][j]*n[j][k] #do the matrix multiplication
    return u

print (matrix(m1,m2))
print (np.matmul(m1,m2)) #Use numpy to check answer


[[ 22.  26.]
 [ 18.  19.]
 [ 53.  64.]
 [-21. -25.]]
[[ 22  26]
 [ 18  19]
 [ 53  64]
 [-21 -25]]


In [ ]:
#Question 2

"""
1) Divide by the first element to get 1 in (0,0) position
2) Take each row and subtract that times their first element to get 0 in the first column [1,0,0,0]
3) Divide by the second element in the second row to get one in the (1,1) position
4) Take the rows below and subtract the second row times their second element
5) Divide by the third element in the third row to get one in the (2,2) position
6) Take the rows below and subtract the third row times their third element
7) Divide by the fourth element in the last row to get one in the (3,3) position

"""


In [2]:
#Question 2

#Make matrix for system of equations
v11 = np.array([[2.0,-1.0,5.0,1.0,-3.0]])
v12 = np.array([[3.0,2.0,2.0,-6.0,-32.0]])
v13 = np.array([[1.0,3.0,3.0,-1.0,-47.0]])
v14 = np.array([[5.0,-2.0,-3.0,3.0,49.0]])
m3 = np.vstack([v11,v12,v13,v14])

v21 = np.array([[-3.0]])
v22 = np.array([[-32.0]])
v23 = np.array([[-47.0]])
v24 = np.array([[49.0]])
m4 = np.vstack([v21,v22,v23,v24])

v31 = np.array([[2.0,-1.0,5.0,1.0]])
v32 = np.array([[3.0,2.0,2.0,-6.0]])
v33 = np.array([[1.0,3.0,3.0,-1.0]])
v34 = np.array([[5.0,-2.0,-3.0,3.0]])
m5 = np.vstack([v31,v32,v33,v34])

def solve(m): #define function to do row reduction
    r1 = m[0]
    r2 = m[1]
    r3 = m[2]
    r4 = m[3]
    #First column
    r1 = r1/m[0][0]
    r2 = r2 - r1*r2[0]
    r3 = r3 - r1*r3[0]
    r4 = r4 - r1*r4[0]
    #second column
    r2 = r2/r2[1]
    r3 = r3 - r2*r3[1]
    r4 = r4 - r2*r4[1]
    #third column
    r3 = r3/r3[2]
    r4 = r4 - r3*r4[2]
    #fourth column
    r4 = r4/r4[3]
    m1 = np.vstack([r1,r2,r3,r4])
    return m1

def solve_better(m): #This function is just a bit shorter because I used for loops
    for i in range(len(m)-1): #first row
        m[0] = m[0]/m[0][0] #get 1 by dividing by its own element
        m[i+1] = m[i+1] - m[0]*m[i+1][0] #Subtract the rows below
    for i in range (len(m)-2): #second row
        m[1] = m[1]/m[1][1]
        m[i+2] = m[i+2] - m[1]*m[i+2][1]
    for i in range(len(m)-3): #third row
        m[2] = m[2]/m[2][2]
        m[i+3] = m[i+3] - m[2]*m[i+3][2]
    m[3] = m[3]/m[3][3] #Last row
    print (m)
    return m

solution = solve_better(m3) 
#solution = (solve(m3))

#Solve for variable using back substitution
z = solution[3][-1]
y = solution[2][-1] - z*solution[2][-2]
x = solution[1][-1] - z*solution[1][-2] - y*solution[1][-3]
w = solution[0][-1] - z*solution[0][-2] - y*solution[0][-3] - x*solution[0][-4]

print ("Solution:\n",w,x,y,z)
print ("Solution:\n",np.linalg.solve(m5,m4)) #check using numpy

[[ 1.         -0.5         2.5         0.5        -1.5       ]
 [ 0.          1.         -1.57142857 -2.14285714 -7.85714286]
 [ 0.          0.          1.          1.         -3.        ]
 [ 0.          0.          0.          1.          1.        ]]
Solution:
 2.0 -12.0 -4.0 1.0000000000000004
Solution:
 [[  2.]
 [-12.]
 [ -4.]
 [  1.]]


In [6]:
#Question 3

v41 = np.array([[2,-1,5]])
v42 = np.array([[3,2,2]])
v43 = np.array([[1,3,-1]])
m5 = np.vstack([v41,v42,v43])

def determinant(m, count):
    if len(m) == len(m[0]): #check if matrix is square
        if len(m) == 2: #set base case as two by two matrix
             return(m[0][0]*m[1][1])-(m[0][1]*m[1][0]) #ad-bc
        else: 
            for i in range (len(m)):# loop through number of rows in matrix
                if i == 0: #for the first row
                    n = m[1:]# cut off first row
                elif i == len(m): #for last row
                    n = m[:len(m)] #cut off last row
                else: #for all other rows
                    o = m[:i]#slice up to, but not including that row
                    p = m[i+1:] #rows after that row
                    n = np.vstack([o,p]) #put back into matrix
                newm = n[:,1:] #cut off first column
                count += ((-1)**(i+2))*m[i][0]*determinant(newm, count) 
            return count
    else:
        print ("The matrix is not square")
    
print (determinant(m5,0))
print (np.linalg.det(m5))# check answer with numpy

14
14.000000000000009
